virtual_sensor:
  ros__parameters:
    dataset: "fbg_10"

virtual_robot:
  ros__parameters:
    dataset: "fbg_10"
    
estimator:
  ros__parameters:
    alpha: 0.65

controller:
  ros__parameters:
    K: -0.01

controller_discrete:
  ros__parameters:
    K: -0.5